apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-sample-app-deployment
spec:
  selector:
    matchLabels:
      app: tomcat-sample-app
  replicas: 1
  template:
    metadata:
      labels:
        app: tomcat-sample-app
    spec:
      containers:
      - name: tomcat-sample-app
    # enter the path to your image, be sure to include the correct region prefix    
        image: mailrahulsre/tomcat-sample-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-sample-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: tomcat-sample-app
